# Generated by Django 5.2.1 on 2025-05-13 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            # SQL para eliminar todas las tablas existentes
            """
            DROP TABLE IF EXISTS payment_service_paymentnotification;
            DROP TABLE IF EXISTS payment_service_paymentrequest;
            DROP TABLE IF EXISTS django_migrations;
            DROP TABLE IF EXISTS django_content_type;
            """,
            # SQL para revertir (no hay)
            reverse_sql=migrations.RunSQL.noop
        )
    ]
