# Generated by Django 5.2.1 on 2025-08-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0003_paymentrequest_order_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='user_token',
            field=models.TextField(help_text='Token de autenticación del usuario'),
        ),
    ]
